name: "Lint for Rails Projects"
on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/build-lint-test-action/setup-env@env-test
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up build
        run: >-
          touch .env.development;
          docker-compose pull web;
          docker-compose pull worker
      - name: Run Rubocop
        run: docker-compose run web bundle exec rubocop --parallel --format progress
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'rubocop*.xml'
